<a href="https://colab.research.google.com/github/philipilono/increasing_randomness/blob/main/marioberta_approach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math
import numpy as np
from scipy.fft import fft, ifft
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
with open('quantum_bitstring.txt', 'r') as file:
  txt = file.read().strip()
  bits1 = np.array([int(bit) for bit in txt])
  #file.write(''.join(str(bit) for row in bits1 for bit in row))
with open('quantum_bitstring_2.txt', 'r') as file:
  txt2 = file.read().strip()
  bits2 =  np.array([int(bit) for bit in txt2])

In [ ]:
print(len(bits1))
print(len(bits2))
# bits2 = bits2[:-1]
# print(len(bits2))

2540000
2540000


In [ ]:
# set security parameter
power = 8
eps = 10**(-power)
print(f"Security parameter: {eps}.")

# set number of output bits
#m = 1000


# set min-entropy rates for sources
k_1 = 0.809031
print(f"Min-entropy rate of first source: {k_1}.")
k_2 = 0.824166
print(f"Min-entropy rate of second source: {k_2}")



#m = int(np.floor(n * (k_1 + k_2 - 1) + 1 - 2 * power))
n = len(bits1)
# required number of input bits (for each source)
# n = math.floor((m-1-2*math.log2(eps))
#     /(k_1+k_2-1))

#m = math.floor((k_1+k_2-n) +1 - 2*math.log2(eps))
m = math.floor((n*k_1+n*k_2-n)
           +1 - 2*math.log2(eps))
print(f"Desired output length: {m} bits.")
print(f"Required length of each input source: {n} bits.")


Security parameter: 1e-08.
Min-entropy rate of first source: 0.809031.
Min-entropy rate of second source: 0.824166
Desired output length: 1608374 bits.
Required length of each input source: 2540000 bits.


In [ ]:
array_one = bits1.reshape(1, n)
array_two = bits2.reshape(1, n)

In [ ]:
array_two_under = np.array(array_two[0,0:n-m])[np.newaxis]
zero_vector = np.zeros((1,n+m-3), dtype=int)
array_two_zeros = np.hstack((array_two_under,zero_vector))
array_two_over = array_two[0,n-m:n][np.newaxis]
array_one_merged = np.zeros((1,2*n-3), dtype=int)
for i in range(m):
    array_one_merged[0,i] = array_one[0,m-1-i]
for j in range(n-m-1):
    array_one_merged[0,n+m-2+j] = array_one[0,n-2-j]

In [ ]:
print(array_two_over.shape)

(1, 1608374)


In [ ]:
output_fft = np.around(ifft(fft(array_one_merged)*fft(array_two_zeros)).real)
output_addition = output_fft[0,0:m] + array_two_over
output_final = output_addition.astype(int) % 2
print(f"The {m} random output bits are:\n{output_final}.")

The 1608374 random output bits are:
[[0 0 1 ... 0 1 1]].


In [ ]:
bits1

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
output_final[0]

array([0, 0, 1, ..., 0, 1, 1])

In [ ]:
print(len(output_final))
print(output_final.shape)

1
(1, 1608374)
